name: Cloudant Backup Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'

jobs:
  cloudant-backup:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create Environment File
        run: |
          cat <<EOF > .env
          COUCH_URL=${{ secrets.COUCH_URL }}
          DATABASES="${{ secrets.DATABASES }}"
          ENV=${{ secrets.ENV }}
          UPLOAD_TO_S3=${{ secrets.UPLOAD_TO_S3 }}
          S3_BUCKET=${{ secrets.S3_BUCKET }}
          S3_ENDPOINT_URL=${{ secrets.S3_ENDPOINT_URL }}
          EOF

      - name: Give Execute Permission
        run: chmod +x manage_cloudant.sh

      - name: Run Backup Script
        run: ./manage_cloudant.sh
